<script type="text/javascript" src="{{asset('js/jquery-3.2.1.min.js')}}"></script>
        <script type="text/javascript" src="{{asset('js/bootstrap.min.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/jquery.slimscroll.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/select2.min.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/moment.min.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/bootstrap-datetimepicker.min.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/app.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/jquery.validate.min.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/additional-methods.js')}}"></script>
		<script type="text/javascript" src="{{asset('js/add_employee.js')}}"></script>